config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :categories
  devise_for :users
  get 'home/search'
  get 'home/index'
  get 'home/purchases'
  get 'home/history'
  get 'home/favorites'
  get 'home/reputation'
  get 'home/sales'
  get 'home/products'
  get 'home/administrator'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/views/partials/_footer.html.erb
<div class="py-2 text-white" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, .75), rgba(0, 0, 0, .75)), url(https://static.pingendo.com/cover-bubble-dark.svg);  background-position: center center, center center;  background-size: cover, cover;  background-repeat: repeat, repeat;" data-pingendo-transient="">
    <div class="container">
      <div class="row">
        <div class="col-md-6 text-center align-self-center p-4">
          <p class="mb-5"> <strong>Pingendo Inc.</strong> <br>795 Folsom Ave, Suite 600 <br>San Francisco, CA 94107 <br> <abbr title="Phone">P:</abbr> (123) 456-7890 </p>
          <div class="row">
            <div class="col-md-12 d-flex align-items-center justify-content-around"> <a href="#">
                <i class="d-block fa fa-facebook-official text-light fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-instagram text-light fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-google-plus-official text-light fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-pinterest-p text-light fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-reddit text-light fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-twitter text-light fa-lg ml-2"></i>
              </a> </div>
          </div>
        </div>
        <div class="col-md-6 p-0"> <iframe width="100%" height="350" src="https://maps.google.com/maps?hl=en&amp;q=New%20York&amp;ie=UTF8&amp;t=&amp;z=14&amp;iwloc=B&amp;output=embed" scrolling="no" frameborder="0"></iframe></div>
      </div>
    </div>
  </div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
    <div class="container"> <a class="navbar-brand text-primary" href="#">
        <i class="fa d-inline fa-lg fa-circle-o"></i>
        <b> Commerce</b>
      </a> <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse" data-target="#navbar5">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar5">
        <ul class="navbar-nav mr-auto">
          <li> <a><%= link_to "Inicio", root_path, class:"nav-item nav-link" %></a> </li>
          <li> <a><%= link_to "Compras", home_purchases_path, class:"nav-item nav-link" %></a> </li>
          <li> <a><%= link_to "Historial", home_history_path, class:"nav-item nav-link" %></a> </li>
          <li> <a><%= link_to "Favoritos", home_favorites_path, class:"nav-item nav-link" %></a> </li>
          <li class="nav-item dropdown" contenteditable="false"> 
            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categorías</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <% @categories.each do |category|%> 
                <%= link_to category.name, category, class:"dropdown-item"%>
              <%end%>
            </div>
          </li>
        </ul>
        <%=form_tag "/home/search", method: :get, class:"form-inline m-8" do%>
        
          <%= text_field_tag :search, params[:search], html: {require:true}, placeholder:"Search", class:"form-control mr-sm-2"%>
          <%= submit_tag "Search",:search => nil, class:"btn btn-outline-success my-sm-0 my-2 mr-1"%>
        <%end%>
        <a class="btn btn-default navbar-btn btn-primary my-2 mx-1">
          <i class="fa fa-shopping-cart my-2"></i>
        </a>
        <%if user_signed_in?%>
          <a><i class="fa fa-user fa-fw my-2"></i><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class:"btn btn-default navbar-btn btn-primary my-2 mx-1" %></a>
        <%else%>
          <a><%= link_to "Ingresar", new_user_session_path, class:"btn btn-default navbar-btn btn-primary my-2 mx-1" %></a>
          <a> <%= link_to "Registro", new_user_registration_path, class:"btn btn-default navbar-btn btn-primary my-2 mx-1" %></a>
        <%end%>
      </div>
    </div>
  </nav>

app/views/partials/_panel.html.erb
<div class="col-md-2" >
  <ul class="nav nav-pills flex-column my-2">
    <div class="card">
      <div class="card-body">
        
        <li class="nav-item">
          <%= link_to "Resumen", home_purchases_path, class: "nav-link fa fa-home fa-home" %>  
        </li>
        <li class="nav-item">
          <%= link_to "Administrador", home_administrator_path, class: "nav-link" %> 
        </li>
        <li class="nav-item">
          <%= link_to "Reputación", home_reputation_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Compras", home_purchases_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Productos", home_products_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Ventas", home_sales_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Configuración",edit_user_registration_path, class:"nav-link" %>
        </li>
      </div>
    </div>
  </ul>
</div>