config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :categories
  devise_for :users
  get 'home/search'
  get 'home/index'
  get 'home/purchases'
  get 'home/history'
  get 'home/favorites'
  get 'home/reputation'
  get 'home/sales'
  get 'home/products'
  get 'home/administrator'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_products, only: [:products, :index]

  def index
  end

  def purchases
  end

  def history
  end

  def favorites
  end

  def reputation
  	
  end

  def sales
  	
  end

  def products
  end

  def search
    @products = Product.where("p_name like :query", query: "%#{params[:search]}%")
  end

  private
  def set_products
    @products = Product.paginate(page: params[:page], per_page: 10)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_index_admin.html.erb
<div class="py-5">
  <div class="container">
    <div class="row">
      <%= render "partials/panel"%>
      <div class="col-md-9">
        <div class="card  p-2" >
          <div class="card-body">
            <h1 class="mb-3 text-center">Resumen</h1>
            <h3 class="mb-2 text-center">Productos</h3>
            <ul class="list-group">
              <li class="list-group-item d-flex justify-content-between align-items-center">Disponibles <span class="badge badge-pill badge-primary">4</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center"> Agotados <span class="badge badge-primary badge-pill">2</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center"> Vendidos <span class="badge badge-primary badge-pill">1</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/administrator.html.erb
<div class="py-5">
  <div class="container">
    <div class="row">
      <%= render "partials/panel"%>
      <div class="col-md-9">
        <div class="card  p-2" >
          <div class="card-body">
            <h1 class="mb-3 text-center">Administrador</h1>
            <ul class="list-group">
              <div class="row">
                <%= link_to "Categorías", categories_path, class:"btn btn-default navbar-btn btn-primary my-2 mx-1" %>
                <%= link_to "Nueva categoría", new_category_path, class:"btn btn-default navbar-btn btn-primary my-2 mx-1" %>
                <%= link_to "Productos", products_path, class:"btn btn-default navbar-btn btn-primary my-2 mx-1" %>
                <%= link_to "Nuevo producto", new_product_path, class:"btn btn-default navbar-btn btn-primary my-2 mx-1" %>
              </div>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/favorites.html.erb
<div class="py-5">
  <div class="container">
    <div class="row">
      <%= render "partials/panel"%>
      <div class="col-md-9">
        <div class="card  p-2" >
          <div class="card-body">
            <h1 class="mb-3 text-center">Resumen</h1>
            <h3 class="mb-2 text-center">Productos</h3>
            <ul class="list-group">
              
              
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/history.html.erb
<div class="py-5">
  <div class="container">
    <div class="row">
      <%= render "partials/panel"%>
      <div class="col-md-9">
        <div class="card  p-2" >
          <div class="card-body">
            <h1 class="mb-3 text-center">Resumen</h1>
            <h3 class="mb-2 text-center">Productos</h3>
            <ul class="list-group">
              
              
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="py-5">
  <div class="container">
    <div class="row">
      <%= render "partials/panel"%>
      <% if !current_user %>
        <div class="col-md-9">     
          <% @products.each do |product|%>
            <div class="card  p-2" >
              <div class="card-body">
                <%= link_to product.p_name, product%> 
                <%= truncate(product.p_description, length:150)%><br>
              </div>
            </div>
          <%end%>
        </div>
        <%= will_paginate @products %>
      <%else%>
        <%render "index_admin"%>
      <%end%>        
    </div>
  </div>
</div>

app/views/home/products.html.erb
<div class="py-5">
  <div class="container">
    <div class="row">
      <%= render "partials/panel"%>
      <div class="col-md-9">
        <div class="card  p-2" >
          <div class="card-body">
            <h1 class="mb-3 text-center">Resumen</h1>
            <h3 class="mb-2 text-center">Productos</h3>
            <ul class="list-group">
              
              <div class="col-md-10">
                <ul class="nav nav-tabs">
                  <li class="nav-item">
                    <a href="" class="active nav-link" data-toggle="tab" data-target="#tabone">Activadas</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="" data-toggle="tab" data-target="#tabtwo">Pausadas</a>
                  </li>
                  <li class="nav-item">
                    <a href="" class="nav-link" data-toggle="tab" data-target="#tabthree">Finalizadas</a>
                  </li>
                </ul>
                <div class="tab-content mt-2">
                  <div class="tab-pane fade show active" id="tabone" role="tabpanel">
                    <div class="card  p-2">
                      <div class="card-body">
                        <div class="row">
                          <% @products.each do |product|%>
                            <div class="col-md-5">
                              <%= "Producto ##{product.id}"%>
                              <p class="my-3">Producto # n</p>
                            </div>
                            <div class="col-md-3">
                              <%= "Disponibles $#{product.p_quantify}"%>
                              <p class="my-3">$ 114 * 4 disponibles</p>
                            </div>
                            <div class="col-md-2 text-right">
                              <div class="btn-group my-2">
                                <button class="btn dropdown-toggle btn-secondary" data-toggle="dropdown">
                                  <i class="fa fa-fw fa-asterisk"></i>
                                </button>
                                <div class="dropdown-menu" style="">
                                  <%= link_to 'Edit', edit_product_path(product), class:"dropdown-item" %>
                                  <td><%= link_to 'Eliminar', product, method: :delete, data: { confirm: 'Are you sure?' }, class:"dropdown-item btn btn-danger" %></td>
                                </div>
                              </div>
                            </div>
                          <%end%>
                        </div>
                        <%= will_paginate @products %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>              
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/purchases.html.erb
<div class="py-5">
  <div class="container">
    <div class="row">
      <%= render "partials/panel"%>
      <div class="col-md-9">
        <div class="card  p-2" >
          <div class="card-body">
            <h1 class="mb-3 text-center">Compras</h1>
             
              <div class="col-md-9">
                <div class="row">
                  <div class="col-md-12">
                    <div class="card  p-1">
                      <div class="card-body">
                        <div class="row">
                          <div class="col-md-6">
                            <h4 class="card-title my-2">Nombre del producto</h4>
                            <h6 class="card-subtitle text-muted">$ 165 . 00 x 1 unidad&nbsp;</h6>
                            <p class="card-text p-y-1">Fecha de compra: 27 de april del 2018</p>
                          </div>
                          <div class="col-md-3">
                            <h4 class="card-title my-2">Jesús Martínez</h4>
                            <h6 class="card-subtitle text-muted">000 000 0000</h6>
                            <a class="card-text p-y-3 btn  my-1">Ver mensajes</a>
                          </div>
                          <div class="col-md-3">
                            <a class="card-text p-y-3 btn my-4" href="purchase.html">Ver detalles</a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/reputation.html.erb
<div class="py-5">
  <div class="container">
    <div class="row">
      <%= render "partials/panel"%>
      <div class="col-md-9">
        <div class="card  p-2" >
          <div class="card-body">
            <h1 class="mb-3 text-center">Resumen</h1>
            <h3 class="mb-2 text-center">Productos</h3>
            <ul class="list-group">
              
              
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/sales.html.erb
<div class="py-5">
  <div class="container">
    <div class="row">
      <%= render "partials/panel"%>
      <div class="col-md-9">
        <div class="card  p-2" >
          <div class="card-body">
            <h1 class="mb-3 text-center">Resumen</h1>
            <h3 class="mb-2 text-center">Productos</h3>
            <ul class="list-group">
              
              
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/search.html.erb
<div class="container py-5">
  <div class="row my-5">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">

          <h1>Products</h1>

          <table>
            <thead>
              <tr>
                <th>name</th>
                <th>description</th>
                <th>price</th>
                <th>quantify</th>
                <th>send</th>
                <th>available</th>
                <th>User</th>
                <th>Categorias</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @products.each do |product| %>
                <tr>
                  <td><%= product.p_name %></td>
                  <td><%= product.p_description %></td>
                  <td><%= product.p_price %></td>
                  <td><%= product.p_quantify %></td>
                  <td><%= product.p_send %></td>
                  <td><%= product.p_available %></td>
                  <td><%= product.user.email %></td>
                  <td>
                    <%product.categories.each do |category|%>
                      <%= link_to category.name, category %>
                    <%end%>                    
                  </td>
                  <td><%= link_to 'Show', product, class:"btn btn-primary" %></td>
                  <td><%= link_to 'Edit', edit_product_path(product), class:"btn btn-primary" %></td>
                  <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <br>

          <%= link_to 'New Product', new_product_path, class:"btn btn-primary" %>
          <%= link_to 'Atras',  home_administrator_path,  class:"btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>