config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :categories
  devise_for :users
  get 'home/search'
  get 'home/index'
  get 'home/purchases'
  get 'home/history'
  get 'home/favorites'
  get 'home/reputation'
  get 'home/sales'
  get 'home/products'
  get 'home/administrator'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id                 :integer          not null, primary key
#  name               :string
#  description        :string
#  c_img_file_name    :string
#  c_img_content_type :string
#  c_img_file_size    :bigint
#  c_img_updated_at   :datetime
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Category < ApplicationRecord
  has_attached_file :c_img,
    styles: {
      thumb: 	{geometry: "500x500>", format: :png, convert_options: " -background white -gravity center -extent 500x500"},
      medium: 	{geometry: "630x315>", format: :png, convert_options: " -background white -gravity center -extent 630x315"},
      big: 		{geometry: "920x560>", format: :png, convert_options: " -background white -gravity center -extent 920x560"},
    },
    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :c_img, content_type: /\Aimage\/.*\z/

  validates :name, presence: true, length: {minimum: 10, too_short: "Minimo son %{count} caracteres."}
  validates :description, presence: true, length: {minimum: 50, too_short: "Minimo son %{count} caracteres."}

  has_many :has_categories, :dependent => :destroy
  has_many :products, through: :has_categories, :dependent => :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  #before_action :set_category, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.paginate(page: params[:page], per_page: 6)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @products = @category.products.paginate(page: params[:page], per_page: 10)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :c_img)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-1.col-md-10">
      <div class="card">
        <div class="card-body">
          <%= form_for @category, builder: BootstrapFormBuilder do |form| %>
            <div class="row">
            
              <%= form.label :name %>
              <%= form.text_field :name %>
            

            
              <%= form.label :description %>
              <%= form.text_field :description %>
            

            
              <%= form.label :Imagen %>
              <%= form.file_field :c_img %>
            

            
              <%= form.submit %>
            </div>
            
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="container py-5">
  <div class="row my-5">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <h1>Categories</h1>

            <table>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th>C img</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @categories.each do |category| %>
                  <tr>
                    <td><%= category.name %></td>
                    <td><%= category.description %></td>
                    <td><%= image_tag category.c_img.url %></td>
                    <td><%= link_to 'Show', category, class:"btn btn-primary" %></td>
                    <td><%= link_to 'Edit', edit_category_path(category), class:"btn btn-primary" %></td>
                    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>  
            <br>
            <%if user_signed_in? && current_user.is_admin? %>
              <%= link_to 'New Category', new_category_path,  class:"btn btn-primary" %>
              <%= link_to 'Atras',  home_administrator_path,  class:"btn btn-primary" %>
            <%end%>
          </div>
        </div>
      </div>
  </div>
  <%= will_paginate @categories %>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-9">
              <div class="row">
                <div class="col-12">
                  <p>
                    <strong>Name:</strong>
                    <%= @category.name %>
                  </p>

                  <p>
                    <strong>Description:</strong>
                    <%= @category.description %>
                  </p>

                  <p>
                    <strong>Imagen:</strong>
                    <%= image_tag @category.c_img.url %>
                  </p>

                  <% if can? :update, @category%>
                    <%= link_to 'Edit', edit_category_path(@category) %> |
                    <%= link_to 'Back', categories_path %>
                  <%end%>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-3 my-5">
        <div class="card h-100">
          <div class="card-body">
            <%= link_to product.p_name, product %>
            <%= "Descripción de producto: #{truncate(product.p_description, length:150)}" %><br>
          </div>
        </div>     
      </div>
    <%end%>
  </div>
  <%= will_paginate @products %>
</div>


       